### ISSUE TITLE
Dumping a Remote Database

### ISSUE THREAD

**Issue by skylarweaver** [cmu-is-projects/ferry#107]
Is ferry able to dump a remote database? I have attempted this with a mysql database located on remote server, but I get this error:

> ferry --dump phenotype
operating with mysql2
mysqldump: Got error: 1044: Access denied for user ''@'localhost' to database 'phenotypes' when selecting the database
"Complete!"

This is what is in my database.yml for the phenotype database:

phenotype:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: phenotypes
  host: pawn.hss.cmu.edu
  username: phenotypes
  password: –––––––––
  socket: /tmp/mysql.sock

**Comment by anthcor** [comment]
Can you clarify what you mean by "remote" database?

**Comment by loganwatanabe** [comment]
Ferry connects to your db through Active Record, so try and see if you can call on active record through your command line first. If you can't, the problem  would be with  your dev environment access. If you can, let us know and we can get into it.

**Comment by anthcor** [comment]
One way to do this would be to make sure that the db is local - ferry currently doesnt support remote exporting. Another way is to have ferry on a remote server, ssh into the server, and run the command on the server.

**Comment by skylarweaver** [comment]
Thanks for the help with this and sorry for my poor response times.




I am developing my project on my local drive and am deploying it to a remote server on digital ocean. There is another database (aside from my development, production, and test databases) that is being accessed by the project that is on a server (the IS Pawn server) which is entirely separate from the digital ocean server that our project is hosted on. I am attempting to export the database that is on the remote server (Pawn). 




From what I understand, ferry does not support this type of export? If so, that’s fine and I can try to find some workarounds.




Thanks again for your help guys.
