### ISSUE TITLE
Options for Import

### ISSUE THREAD

**Issue by loganwatanabe** [cmu-is-projects/ferry#32]
As mentioned when I first merged the import functionality, other importers give the option to validate the data against AR before inserting, and also automatically generating PKs for the data if they do not have any.
I think the PK generation would be simple, just need to query the db for the index of the table.  But we'd need a case if the PK is not the default "id" field.  Then we can assign that to the record and import it.

For the validation, I think that is best left out for now.  The dbs should have the basic type validation, but beyond that it might be a big performance hit if we need to check every row of import data against a model.

**Comment by anthcor** [comment]
Actually - do we still want to revisit this?

**Comment by anthcor** [comment]
See #99
